language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t php-nginx-alpine .
  - docker run -d -p 127.0.0.1:80:80 --name php-nginx-alpine-by-jared-test php-nginx-alpine

before_script:
  - pip install -r .travis/requirements.txt

script:
  - docker ps
  - sleep 5
  - curl -I 127.0.0.1:80
  - python .travis/tests.py

notifications:
  slack: kissjared:sKjBTxRxRkqNzCV5NFyP
